apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.spike.local
spec:
  scope: Namespaced
  group: spike.local
  version: v1alpha1
  names:
    kind: Subscription
    plural: subscriptions
    singular: subscription
